config/routes.rb
Fmbstore::Application.routes.draw do


  #get '/test', :to => 'tests#index'
  #get '/test/:id', :to => 'tests#show'

  resources :tests

  #get "administration/index"

  #get "administration/users"

  #get "reports/index"

  #get "reports/sales"

  #resources :onboards
  #get "onboard/new"
  #
  #post "onboard/create" => "onboard#create", :as => :onboard_create
  #
  #get "onboard/show"
  #
  #get "onboard/edit"

  resources :authorizes

  resources :locations

  resources :standings

  resources :paymethods

  #
  #get 'portal', :to => 'portal#index'
  #
  #get "portal/new"
  #
  #get "portal/show"

 resources :comments



  resources :basemetals


  resources :metals


  resources :stones

  resources :eyecolors
  resources :genders
  resources :items
  resources :licenses
  resources :languages
  resources :cellcarriers

  resources :metals
  resources :months
  resources :payments
  resources :products
  resources :productcategories
  resources :purchases

  get 'quotes/current', :to => 'quotes#current'
  resources :quotes
  resources :ratingsystems
  resources :sellers
  resources :states
  resources :stoneclarities
  resources :stonecolors
  resources :stonecuts

  get 'stores/current', :to => 'stores#current'
  get 'stores/list', :to => 'stores#list'


  resources :stonesizes
  resources :stonetypes
  resources :tags
  resources :unitsizes
  resources :unitweights

  #get 'users/current', :to => 'users#current'

  devise_for :users


  #get 'admin/users/clientedit', :to => 'users#clientedit'
  scope '/admin' do
    get 'users/new_owner', :to => 'users#new_owner'
    resources :users
  end

  #resources :buyers
  #resources :managers


  #get "home/index"



  resources :accounts do
    resources :stores, :users

    #resources :commen
    # clts
  end

 # scope '/accounts' do
    put 'send_temp_password/:account_id/user/:id', to: 'users#send_temp_password', as: :send_temp_password
    get 'administration', to: 'administration#index'
    get 'reports', to: 'reports#index'
 # end


  #send to authenticated index page when logged in
  authenticated :user do
    root :to => 'home#index'
  end
  # send to unauthenticated user index page
  root :to => 'home#welcome'


  #get 'authorizes/list_stores', :to => 'authorizes#list_stores'
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :number, :processed, :purchase_id, :release
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tags }
    end
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
    @tag = Tag.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tag }
    end
  end

  # GET /tags/new
  # GET /tags/new.json
  def new
    @tag = Tag.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tag }
    end
  end

  # GET /tags/1/edit
  def edit
    @tag = Tag.find(params[:id])
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(params[:tag])

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render json: @tag, status: :created, location: @tag }
      else
        format.html { render action: "new" }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tags/1
  # PUT /tags/1.json
  def update
    @tag = Tag.find(params[:id])

    respond_to do |format|
      if @tag.update_attributes(params[:tag])
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy

    respond_to do |format|
      format.html { redirect_to tags_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<%= simple_form_for(@tag) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :number %>
    <%= f.input :purchase_id %>
    <%= f.input :release %>
    <%= f.input :processed %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<h1>Editing tag</h1>

<%= render 'form' %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<h1>Listing tags</h1>

<table>
  <tr>
    <th>Number</th>
    <th>Purchase</th>
    <th>Release</th>
    <th>Processed</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tags.each do |tag| %>
  <tr>
    <td><%= tag.number %></td>
    <td><%= tag.purchase_id %></td>
    <td><%= tag.release %></td>
    <td><%= tag.processed %></td>
    <td><%= link_to 'Show', tag %></td>
    <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
    <td><%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Tag', new_tag_path %>

app/views/tags/new.html.erb
<h1>New tag</h1>

<%= render 'form' %>

<%= link_to 'Back', tags_path %>

app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Number:</b>
  <%= @tag.number %>
</p>

<p>
  <b>Purchase:</b>
  <%= @tag.purchase_id %>
</p>

<p>
  <b>Release:</b>
  <%= @tag.release %>
</p>

<p>
  <b>Processed:</b>
  <%= @tag.processed %>
</p>


<%= link_to 'Edit', edit_tag_path(@tag) %> |
<%= link_to 'Back', tags_path %>