config/routes.rb
Fmbstore::Application.routes.draw do


  #get '/test', :to => 'tests#index'
  #get '/test/:id', :to => 'tests#show'

  resources :tests

  #get "administration/index"

  #get "administration/users"

  #get "reports/index"

  #get "reports/sales"

  #resources :onboards
  #get "onboard/new"
  #
  #post "onboard/create" => "onboard#create", :as => :onboard_create
  #
  #get "onboard/show"
  #
  #get "onboard/edit"

  resources :authorizes

  resources :locations

  resources :standings

  resources :paymethods

  #
  #get 'portal', :to => 'portal#index'
  #
  #get "portal/new"
  #
  #get "portal/show"

 resources :comments



  resources :basemetals


  resources :metals


  resources :stones

  resources :eyecolors
  resources :genders
  resources :items
  resources :licenses
  resources :languages
  resources :cellcarriers

  resources :metals
  resources :months
  resources :payments
  resources :products
  resources :productcategories
  resources :purchases

  get 'quotes/current', :to => 'quotes#current'
  resources :quotes
  resources :ratingsystems
  resources :sellers
  resources :states
  resources :stoneclarities
  resources :stonecolors
  resources :stonecuts

  get 'stores/current', :to => 'stores#current'
  get 'stores/list', :to => 'stores#list'


  resources :stonesizes
  resources :stonetypes
  resources :tags
  resources :unitsizes
  resources :unitweights

  #get 'users/current', :to => 'users#current'

  devise_for :users


  #get 'admin/users/clientedit', :to => 'users#clientedit'
  scope '/admin' do
    get 'users/new_owner', :to => 'users#new_owner'
    resources :users
  end

  #resources :buyers
  #resources :managers


  #get "home/index"



  resources :accounts do
    resources :stores, :users

    #resources :commen
    # clts
  end

 # scope '/accounts' do
    put 'send_temp_password/:account_id/user/:id', to: 'users#send_temp_password', as: :send_temp_password
    get 'administration', to: 'administration#index'
    get 'reports', to: 'reports#index'
 # end


  #send to authenticated index page when logged in
  authenticated :user do
    root :to => 'home#index'
  end
  # send to unauthenticated user index page
  root :to => 'home#welcome'


  #get 'authorizes/list_stores', :to => 'authorizes#list_stores'
end

app/controllers/authorizes_controller.rb
class AuthorizesController < ApplicationController


 # before_filter :verify_account, :only => :create
 # before_filter :account_details

  #before_filter :load_authorize_service
  #before_filter :account_authorized?

  # GET /authorizes
  # GET /authorizes.json
  def index
    @authorizes = Authorize.all

    #auth = Services::Authorize.new(current_user, app_store_id)
    #
    #if auth.flash_messages
    #  puts 'flash count'
    #  flash[:notice] = auth.flash_messages[0]
    #  flash[:notice] = auth.flash_messages[1]
    #  puts auth.flash_messages
    #end
    #r = Services::Roles.new('test role')



    #auth.puts_account_details
    #auth.account_authorized?


    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @authorizes }
    end
  end

  # GET /authorizes/1
  # GET /authorizes/1.json
  def show
    @authorize = Authorize.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @authorize }
    end
  end

  # GET /authorizes/new
  # GET /authorizes/new.json
  def new
    @authorize = Authorize.new
    @authorize.user_id = current_user.id
    @license = '1'
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @authorize }
    end
  end

  # GET /authorizes/1/edit
  def edit
    @authorize = Authorize.find(params[:id])
  end

  # POST /authorizes
  # POST /authorizes.json
  def create
    @authorize = Authorize.new(params[:authorize])

    respond_to do |format|
      if @authorize.save
        format.html { redirect_to @authorize, notice: 'Authorize was successfully created.' }
        format.json { render json: @authorize, status: :created, location: @authorize }
      else
        format.html { render action: "new" }
        format.json { render json: @authorize.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /authorizes/1
  # PUT /authorizes/1.json
  def update
    @authorize = Authorize.find(params[:id])

    respond_to do |format|
      if @authorize.update_attributes(params[:authorize])
        format.html { redirect_to @authorize, notice: 'Authorize was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @authorize.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authorizes/1
  # DELETE /authorizes/1.json
  def destroy
    @authorize = Authorize.find(params[:id])
    @authorize.destroy

    respond_to do |format|
      format.html { redirect_to authorizes_url }
      format.json { head :no_content }
    end
  end

private


  def load_authorize_service(service = AuthorizeService.new)
    @authorize_service ||= service
  end

  ##Is the account paid through today?
  #def account_authorized?
  #  #@account_status = Authorize.where("store_id = ?", @store.id)
  #  @expiration_date = @authorize_details[0].expiration_date
  #  puts @expiration_date
  #  puts Date.today
  #  @days_left = (@expiration_date - Date.today).to_i
  #  puts @days_left
  #
  #  if @days_left > 60
  #    true
  #  elsif @days_left < 60 && @days_left > 15
  #    true
  #    puts "License expiring soon, you have #{@days_left} days left."
  #  elsif @days_left < 15 && @days_left > 7
  #    true
  #    puts "Notice: License expiring soon, you have #{@days_left} days left."
  #    flash[:warning] = "License expiring soon, you have #{@days_left} days left."
  #
  #  elsif @days_left < 8
  #    true
  #    puts "Alert: License expiring soon, you have #{@days_left} days left."
  #    flash[:notice] = "License expiring soon, you only have #{@days_left} days left."
  #  else @days_left < 0
  #    false
  #    puts 'Your annual license has expired. Please call to renew.'
  #    #Display alert message
  #
  #  end
  #
  #
  #end

  #def account_details
  #  @user_id = current_user.id
  #  @store = Store.find(app_store_id)
  #  @authorize_details = Authorize.where("store_id = ?", @store.id).active
  #  #puts @store.inspect
  #  #puts @authorize_details.inspect
  #  #puts "current_user.id #{@user_id}"
  #  #puts "store.id #{@store.id}"
  #  #puts "store license #{@store.license}"
  #end


  def verify_account

    false
  end
end

app/helpers/authorizes_helper.rb
module AuthorizesHelper
end

app/views/authorizes/_form.html.erb
<%= simple_form_for(@authorize) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :store, :include_blank => false, :label_method => lambda { |store| "#{store.name} #{store.city} #{store.zipcode}" } %>
    <%= f.association :user, :disabled => true, :include_blank => false, :label_method => lambda { |user| "#{user.first_name} #{user.last_name}" } %>
    <%#= f.input :active %>
    <%#= f.input :license %>
    <%= f.input :payment %>
    <%= f.input :payment_date %>
    <%= f.association :paymethod %>
    <%= f.input :payment_note %>
    <%#= f.input :expiration_date %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/authorizes/edit.html.erb
<h1>Editing authorize</h1>

<%= render 'form' %>

<%= link_to 'Show', @authorize %> |
<%= link_to 'Back', authorizes_path %>

app/views/authorizes/index.html.erb
<h1>Listing authorizes</h1>

<table>
  <tr>
    <th>Store</th>
    <th>User</th>
    <th>Active</th>
    <th>Payment date</th>
    <th>Payment amount</th>
    <th>Paymethod</th>
    <th>Payment note</th>
    <th>Expiration date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @authorizes.each do |authorize| %>
  <tr>
    <td><%= authorize.store_id %></td>
    <td><%= authorize.user_id %></td>
    <td><%= authorize.active %></td>
    <td><%= authorize.payment_date %></td>
    <td><%= authorize.payment %></td>
    <td><%= authorize.paymethod_id %></td>
    <td><%= authorize.payment_note %></td>
    <td><%= authorize.expiration_date %></td>
    <td><%= link_to 'Show', authorize %></td>
    <td><%= link_to 'Edit', edit_authorize_path(authorize) %></td>
    <td><%= link_to 'Destroy', authorize, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Authorize', new_authorize_path %>

app/views/authorizes/list_stores.html.erb
<h3>Authorizations for <%= @account_name %></h3>

<table class="table table-striped">
  <tr>
    <th><%= t('authorize.store') %></th>
    <th><%= t('authorize.expire_date')%></th>
    <th><%= t('authorize.grace') %></th>
    <th><%= t('authorize.user') %></th>
    <th><%= t('authorize.renewal_date') %></th>
  </tr>

<% @authorizes.each do |authorize| %>
  <tr>
    <td><%= link_to authorize.store.name, authorize_path(authorize.id)  %></td>
    <td><%= authorize.expiration_date %></td>
    <td><%= authorize.grace %></td>
    <td><%= authorize.user_id %></td>
    <td><%= authorize.renewal_date %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Authorize', new_authorize_path %>

app/views/authorizes/new.html.erb
<h1>New authorize</h1>

<%= render 'form' %>

<%= link_to 'Back', authorizes_path %>

app/views/authorizes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Store:</b>
  <%= @authorize.store_id %>
</p>

<p>
  <b>User:</b>
  <%= @authorize.user_id %>
</p>

<p>
  <b>Active:</b>
  <%= @authorize.active %>
</p>

<p>
  <b>Payment date:</b>
  <%= @authorize.payment_date %>
</p>

<p>
  <b>Payment amount:</b>
  <%= currency_symbol %><%= @authorize.payment %>
</p>

<p>
  <b>Paymethod:</b>
  <%= @authorize.paymethod_id %>
</p>

<p>
  <b>Payment note:</b>
  <%= @authorize.payment_note %>
</p>

<p>
  <b>Expiration date:</b>
  <%= @authorize.expiration_date %>
</p>


<%= link_to 'Edit', edit_authorize_path(@authorize) %> |
<%= link_to 'Back', authorizes_path %>