config/routes.rb
Fmbstore::Application.routes.draw do


  #get '/test', :to => 'tests#index'
  #get '/test/:id', :to => 'tests#show'

  resources :tests

  #get "administration/index"

  #get "administration/users"

  #get "reports/index"

  #get "reports/sales"

  #resources :onboards
  #get "onboard/new"
  #
  #post "onboard/create" => "onboard#create", :as => :onboard_create
  #
  #get "onboard/show"
  #
  #get "onboard/edit"

  resources :authorizes

  resources :locations

  resources :standings

  resources :paymethods

  #
  #get 'portal', :to => 'portal#index'
  #
  #get "portal/new"
  #
  #get "portal/show"

 resources :comments



  resources :basemetals


  resources :metals


  resources :stones

  resources :eyecolors
  resources :genders
  resources :items
  resources :licenses
  resources :languages
  resources :cellcarriers

  resources :metals
  resources :months
  resources :payments
  resources :products
  resources :productcategories
  resources :purchases

  get 'quotes/current', :to => 'quotes#current'
  resources :quotes
  resources :ratingsystems
  resources :sellers
  resources :states
  resources :stoneclarities
  resources :stonecolors
  resources :stonecuts

  get 'stores/current', :to => 'stores#current'
  get 'stores/list', :to => 'stores#list'


  resources :stonesizes
  resources :stonetypes
  resources :tags
  resources :unitsizes
  resources :unitweights

  #get 'users/current', :to => 'users#current'

  devise_for :users


  #get 'admin/users/clientedit', :to => 'users#clientedit'
  scope '/admin' do
    get 'users/new_owner', :to => 'users#new_owner'
    resources :users
  end

  #resources :buyers
  #resources :managers


  #get "home/index"



  resources :accounts do
    resources :stores, :users

    #resources :commen
    # clts
  end

 # scope '/accounts' do
    put 'send_temp_password/:account_id/user/:id', to: 'users#send_temp_password', as: :send_temp_password
    get 'administration', to: 'administration#index'
    get 'reports', to: 'reports#index'
 # end


  #send to authenticated index page when logged in
  authenticated :user do
    root :to => 'home#index'
  end
  # send to unauthenticated user index page
  root :to => 'home#welcome'


  #get 'authorizes/list_stores', :to => 'authorizes#list_stores'
end

app/models/stonecut.rb
class Stonecut < ActiveRecord::Base
  attr_accessible :abbreviation, :description, :language_id, :name, :sort

  belongs_to :language
end

app/controllers/stonecuts_controller.rb
class StonecutsController < ApplicationController
  # GET /stonecuts
  # GET /stonecuts.json
  def index
    @stonecuts = Stonecut.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @stonecuts }
    end
  end

  # GET /stonecuts/1
  # GET /stonecuts/1.json
  def show
    @stonecut = Stonecut.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @stonecut }
    end
  end

  # GET /stonecuts/new
  # GET /stonecuts/new.json
  def new
    @stonecut = Stonecut.new
    #set defaults
    @stonecut.language_id = 1
    @stonecut.sort = 1
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @stonecut }
    end
  end

  # GET /stonecuts/1/edit
  def edit
    @stonecut = Stonecut.find(params[:id])
  end

  # POST /stonecuts
  # POST /stonecuts.json
  def create
    @stonecut = Stonecut.new(params[:stonecut])

    respond_to do |format|
      if @stonecut.save
        format.html { redirect_to @stonecut, notice: 'Stonecut was successfully created.' }
        format.json { render json: @stonecut, status: :created, location: @stonecut }
      else
        format.html { render action: "new" }
        format.json { render json: @stonecut.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /stonecuts/1
  # PUT /stonecuts/1.json
  def update
    @stonecut = Stonecut.find(params[:id])

    respond_to do |format|
      if @stonecut.update_attributes(params[:stonecut])
        format.html { redirect_to @stonecut, notice: 'Stonecut was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @stonecut.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stonecuts/1
  # DELETE /stonecuts/1.json
  def destroy
    @stonecut = Stonecut.find(params[:id])
    @stonecut.destroy

    respond_to do |format|
      format.html { redirect_to stonecuts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/stonecuts_helper.rb
module StonecutsHelper
end

app/views/stonecuts/_form.html.erb
<%= simple_form_for(@stonecut) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :language, include_blank: false, label_method: 'language_title' %>
    <%= f.input :sort %>
    <%= f.input :name %>
    <%= f.input :abbreviation %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/stonecuts/edit.html.erb
<h1>Editing stonecut</h1>

<%= render 'form' %>

<%= link_to 'Show', @stonecut %> |
<%= link_to 'Back', stonecuts_path %>

app/views/stonecuts/index.html.erb
<legend>Listing stonecuts</legend>

<table class='table'>
  <tr>
    <th>Language</th>
    <th>Sort</th>
    <th>Name</th>
    <th>Abbreviation</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @stonecuts.each do |stonecut| %>
  <tr>
    <td><%= stonecut.language.description %></td>
    <td><%= stonecut.sort %></td>
    <td><%= stonecut.name %></td>
    <td><%= stonecut.abbreviation %></td>
    <td><%= stonecut.description %></td>
    <td><%= link_to 'Show', stonecut %></td>
    <td><%= link_to 'Edit', edit_stonecut_path(stonecut) %></td>
    <td><%= link_to 'Destroy', stonecut, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Stonecut', new_stonecut_path %>

app/views/stonecuts/new.html.erb
<h1>New stonecut</h1>

<%= render 'form' %>

<%= link_to 'Back', stonecuts_path %>

app/views/stonecuts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Language:</b>
  <%= @stonecut.language.description %>
</p>

<p>
  <b>Sort:</b>
  <%= @stonecut.sort %>
</p>

<p>
  <b>Name:</b>
  <%= @stonecut.name %>
</p>

<p>
  <b>Abbreviation:</b>
  <%= @stonecut.abbreviation %>
</p>

<p>
  <b>Description:</b>
  <%= @stonecut.description %>
</p>


<%= link_to 'Edit', edit_stonecut_path(@stonecut) %> |
<%= link_to 'Back', stonecuts_path %>