config/routes.rb
Fmbstore::Application.routes.draw do


  #get '/test', :to => 'tests#index'
  #get '/test/:id', :to => 'tests#show'

  resources :tests

  #get "administration/index"

  #get "administration/users"

  #get "reports/index"

  #get "reports/sales"

  #resources :onboards
  #get "onboard/new"
  #
  #post "onboard/create" => "onboard#create", :as => :onboard_create
  #
  #get "onboard/show"
  #
  #get "onboard/edit"

  resources :authorizes

  resources :locations

  resources :standings

  resources :paymethods

  #
  #get 'portal', :to => 'portal#index'
  #
  #get "portal/new"
  #
  #get "portal/show"

 resources :comments



  resources :basemetals


  resources :metals


  resources :stones

  resources :eyecolors
  resources :genders
  resources :items
  resources :licenses
  resources :languages
  resources :cellcarriers

  resources :metals
  resources :months
  resources :payments
  resources :products
  resources :productcategories
  resources :purchases

  get 'quotes/current', :to => 'quotes#current'
  resources :quotes
  resources :ratingsystems
  resources :sellers
  resources :states
  resources :stoneclarities
  resources :stonecolors
  resources :stonecuts

  get 'stores/current', :to => 'stores#current'
  get 'stores/list', :to => 'stores#list'


  resources :stonesizes
  resources :stonetypes
  resources :tags
  resources :unitsizes
  resources :unitweights

  #get 'users/current', :to => 'users#current'

  devise_for :users


  #get 'admin/users/clientedit', :to => 'users#clientedit'
  scope '/admin' do
    get 'users/new_owner', :to => 'users#new_owner'
    resources :users
  end

  #resources :buyers
  #resources :managers


  #get "home/index"



  resources :accounts do
    resources :stores, :users

    #resources :commen
    # clts
  end

 # scope '/accounts' do
    put 'send_temp_password/:account_id/user/:id', to: 'users#send_temp_password', as: :send_temp_password
    get 'administration', to: 'administration#index'
    get 'reports', to: 'reports#index'
 # end


  #send to authenticated index page when logged in
  authenticated :user do
    root :to => 'home#index'
  end
  # send to unauthenticated user index page
  root :to => 'home#welcome'


  #get 'authorizes/list_stores', :to => 'authorizes#list_stores'
end

app/models/stonecolor.rb
class Stonecolor < ActiveRecord::Base
  attr_accessible :ratingsystem_id, :abbreviation, :description, :language_id, :method, :name, :sort

  belongs_to :language
  belongs_to :ratingsystem

end

app/controllers/stonecolors_controller.rb
class StonecolorsController < ApplicationController
  # GET /stonecolors
  # GET /stonecolors.json
  def index
    @stonecolors = Stonecolor.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @stonecolors }
    end
  end

  # GET /stonecolors/1
  # GET /stonecolors/1.json
  def show
    @stonecolor = Stonecolor.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @stonecolor }
    end
  end

  # GET /stonecolors/new
  # GET /stonecolors/new.json
  def new
    @stonecolor = Stonecolor.new

    #Set defaults
    @stonecolor.language_id = 1

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @stonecolor }
    end
  end

  # GET /stonecolors/1/edit
  def edit
    @stonecolor = Stonecolor.find(params[:id])
  end

  # POST /stonecolors
  # POST /stonecolors.json
  def create
    @stonecolor = Stonecolor.new(params[:stonecolor])

    respond_to do |format|
      if @stonecolor.save
        format.html { redirect_to @stonecolor, notice: 'Stonecolor was successfully created.' }
        format.json { render json: @stonecolor, status: :created, location: @stonecolor }
      else
        format.html { render action: "new" }
        format.json { render json: @stonecolor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /stonecolors/1
  # PUT /stonecolors/1.json
  def update
    @stonecolor = Stonecolor.find(params[:id])

    respond_to do |format|
      if @stonecolor.update_attributes(params[:stonecolor])
        format.html { redirect_to @stonecolor, notice: 'Stonecolor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @stonecolor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stonecolors/1
  # DELETE /stonecolors/1.json
  def destroy
    @stonecolor = Stonecolor.find(params[:id])
    @stonecolor.destroy

    respond_to do |format|
      format.html { redirect_to stonecolors_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/stonecolors_helper.rb
module StonecolorsHelper
end

app/views/stonecolors/_form.html.erb
<%= simple_form_for(@stonecolor) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :language, label_method: 'language_title' %>
    <%= f.association :ratingsystem, include_blank: true, label_method: 'listbox_stonecolor' %>
    <%= f.input :sort %>
    <%= f.input :name %>
    <%= f.input :abbreviation %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/stonecolors/edit.html.erb
<h1>Editing stonecolor</h1>

<%= render 'form' %>

<%= link_to 'Show', @stonecolor %> |
<%= link_to 'Back', stonecolors_path %>

app/views/stonecolors/index.html.erb
<h1>Listing stonecolors</h1>

<table class='table'>
  <tr>
    <th>Language</th>
    <th>System</th>
    <th>Sort</th>
    <th>Name</th>
    <th>Abbreviation</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @stonecolors.each do |stonecolor| %>
  <tr>
    <td><%= stonecolor.language.description %></td>
    <td><%= stonecolor.ratingsystem.abbreviation %></td>
    <td><%= stonecolor.sort %></td>
    <td><%= stonecolor.name %></td>
    <td><%= stonecolor.abbreviation %></td>
    <td><%= stonecolor.description %></td>
    <td><%= link_to 'Show', stonecolor %></td>
    <td><%= link_to 'Edit', edit_stonecolor_path(stonecolor) %></td>
    <td><%= link_to 'Destroy', stonecolor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Stonecolor', new_stonecolor_path %>

app/views/stonecolors/new.html.erb
<h1>New stonecolor</h1>

<%= render 'form' %>

<%= link_to 'Back', stonecolors_path %>

app/views/stonecolors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Language:</b>
  <%= @stonecolor.language_id %>
</p>

<p>
  <b>System:</b>
  <%= @stonecolor.ratingsystem.abbreviation %>
</p>

<p>
  <b>Sort:</b>
  <%= @stonecolor.sort %>
</p>

<p>
  <b>Name:</b>
  <%= @stonecolor.name %>
</p>

<p>
  <b>Abbreviation:</b>
  <%= @stonecolor.abbreviation %>
</p>

<p>
  <b>Description:</b>
  <%= @stonecolor.description %>
</p>


<%= link_to 'Edit', edit_stonecolor_path(@stonecolor) %> |
<%= link_to 'Back', stonecolors_path %>